[package]
name = "rbxmath/spline"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MPL-2.0"
authors = ["AstroCode"]
exclude = ["test"]

[dependencies]
Interpolation = "rbxmath/interpolation@0.1.2"