[package]
name = "ukendio/matrices"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MPL-2.0"
authors = ["Aidan Epperly"]

[dependencies]
Scalars = "ukendio/scalars@0.1.0"
Tools = "ukendio/tools@0.1.0"
