[package]
name = "rbxmath/rbxmath"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MPL-2.0"
authors = ["Aidan Epperly", "Ethan Curtiss"]
exclude = ["testing", "Packages", "libraries"]

[dependencies]
FastFourierTransform = "rbxmath/fast-fourier-transform@0.1.0"
Graphs = "rbxmath/graphs@0.1.1"
Interpolation = "rbxmath/interpolation@0.1.1"
Matrices = "rbxmath/matrices@0.1.0"
Noise = "rbxmath/noise@0.1.0"
NumericalMethods = "rbxmath/numerical-methods@0.1.0"
Ode = "rbxmath/ode@0.1.0"
PrimeList = "rbxmath/primelist@0.2.0"
Primes = "rbxmath/primes@0.2.0"
Scalars = "rbxmath/scalars@0.1.0"
Sets = "rbxmath/sets@0.1.0"
Spline = "rbxmath/spline@0.1.4"
Tools = "rbxmath/tools@0.2.0"
