[package]
name = "ukendio/spline"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MPL-2.0"
authors = ["Ethan Curtiss"]
exclude = ["test"]

[dependencies]
FastFourierTransform = "ukendio/fast-fourier-transform@0.1.0"
Interpolation = "ukendio/interpolation@0.1.0"
Matrices = "ukendio/matrices@0.1.2"
PrimeList = "ukendio/primelist@0.1.2"
Primes = "ukendio/primes@0.1.0"
Scalars = "ukendio/scalars@0.1.0"
Tools = "ukendio/tools@0.1.0"